export const GUIAS = {
  cdmx: "Ciudad_de_México",
  "roma-condesa": "Ciudad_de_México",
  polanco: "Ciudad_de_México",
  "zona-rosa": "Ciudad_de_México",
  coyoacan: "Ciudad_de_México",
  "edomex-satelite": "Ciudad_de_México",
  toluca: "Toluca",
  metepec: "Toluca",
  cuernavaca: "Cuernavaca",
  acapulco: "Acapulco",
  "costera-aca": "Acapulco",
  cancun: "Cancún",
  "hotel-cancun": "Cancún",
  playa: "Playa_del_Carmen",
  tulum: "Tulum",
  vallarta: "Puerto_Vallarta",
  cabos: "Los_Cabos",
  mazatlan: "Mazatlán",
};
